@extends('partials.layouts.master')

@section('title', 'Page | Urbix Admin & Dashboards Template')
@section('title-sub', 'Page')
@section('pagetitle', 'Timeline')

@section('content')

            <div class="row">
                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title">Basic Timeline</h5>
                        </div>
                        <div class="card-body">
                            <div class="timeline2">
                                <ul>
                                    <li class="box">
                                        <span></span>
                                        <div class="title">April 2024</div>
                                        <div class="sub-title">created by MARK</div>
                                        <div class="info">Lorem ipsum dolor, sit amet consectetur adipisicing elit. Perferendis, corrupti.</div>
                                        <div class="time">
                                            <span>12:00pm</span>
                                            <span>4:45am</span>
                                        </div>
                                    </li>
                                    <li class="box">
                                        <span></span>
                                        <div class="title">May 2024</div>
                                        <div class="sub-title">created by MARK</div>
                                        <div class="info">Lorem ipsum dolor sit amet.</div>
                                        <div class="time">
                                            <span>7:00am</span>
                                            <span>11:30</span>
                                        </div>
                                    </li>
                                    <li class="box">
                                        <span></span>
                                        <div class="title">Jun</div>
                                        <div class="sub-title">created by MARK</div>
                                        <div class="info">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Veniam iste perspiciatis eos eum rerum amet!</div>
                                        <div class="time">
                                            <span>1:00pm</span>
                                            <span>5:00pm</span>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title">Basic Timeline</h5>
                        </div>
                        <div class="card-body">
                            <div class="timeline2 icon-timeline">
                                <ul>
                                    <li class="box">
                                        <span class="bg-primary">
                                            <i class="ri-file-text-line"></i>
                                        </span>
                                        <div class="title">April 2024</div>
                                        <div class="sub-title">Generated by Sarah K.</div>
                                        <div class="info">Invoice reports and billing summaries were finalized and exported.</div>
                                        <div class="time">
                                            <span>09:00am</span>
                                            <span>02:30pm</span>
                                        </div>
                                    </li>

                                    <li class="box">
                                        <span class="bg-warning">
                                            <i class="ri-upload-cloud-line"></i>
                                        </span>
                                        <div class="title">May 2024</div>
                                        <div class="sub-title">Uploaded by Admin</div>
                                        <div class="info">Backup files and plan documentation were successfully uploaded to the cloud.</div>
                                        <div class="time">
                                            <span>10:45am</span>
                                            <span>03:15pm</span>
                                        </div>
                                    </li>

                                    <li class="box">
                                        <span class="bg-info">
                                            <i class="ri-settings-3-line"></i>
                                        </span>
                                        <div class="title">June 2024</div>
                                        <div class="sub-title">Updated by DevOps</div>
                                        <div class="info">System maintenance completed with updates to security and performance settings.</div>
                                        <div class="time">
                                            <span>01:00pm</span>
                                            <span>05:30pm</span>
                                        </div>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </div>
                </div>
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="card-title">Advance Timeline</h5>
                        </div>
                        <div class="card-body">
                            <ul class="timeline">
                                <li>
                                    <div class="card direction-l border-0 shadow-lg">
                                        <div class="card-body text-center flag">
                                            <h4 class="mb-1">April 2024</h4>
                                            <p class="desc text-muted">WooCommerce integration, release of Point of Sale system</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="card direction-r border-0 shadow-lg">
                                        <div class="card-body text-center flag">
                                            <h4 class="mb-1">March 2024</h4>
                                            <p class="desc text-muted">WooCommerce integration, release of Point of Sale system</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="card direction-l border-0 shadow-lg">
                                        <div class="card-body text-center flag xl">
                                            <h4 class="mb-1">May 2024 </h4>
                                            <p class="desc text-muted">WooCommerce integration, release of Point of Sale system</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="card direction-r border-0 shadow-lg">
                                        <div class="card-body text-center flag">
                                            <h4 class="mb-1">June 2024</h4>
                                            <p class="desc text-muted">Shopify integration, Cometa Token private sale for early investors and ICO</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="card direction-l border-0 shadow-lg">
                                        <div class="card-body text-center flag">
                                            <h4 class="mb-1">July</h4>
                                            <div class="desc text-muted">Shopify integration, Cometa Token private sale for early investors and ICO</div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

        </div><!--End container-fluid-->
    </main><!--End app-wrapper-->

@endsection

@section('js')
<!-- App js -->
<script src="assets/js/app.js"></script>

@endsection